# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NopywerPlugin
                                 A QGIS plugin
 power grid analysis and design tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-25
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Victor Finel
        email                : victor.finel.pro@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from qgis.core import QgsProject, QgsVectorLayer
from qgis.PyQt.QtCore import Qt

# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the dialog
from .nopywer_plugin_dialog import NopywerPluginDialog
import os.path


class NopywerPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "NopywerPlugin_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&nopywer")

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("NopywerPlugin", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ":/plugins/nopywer_plugin/icon.png"
        self.add_action(
            icon_path,
            text=self.tr("select layers"),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr("&nopywer"), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = NopywerPluginDialog()
            # Link buttons to functions
            self.dlg.btnAnalysis.clicked.connect(self.npw_analysis)

        # --- Populate the lists of layers ---
        self.populate_layer_list(self.dlg.listLoads)
        self.populate_layer_list(self.dlg.listCables)
        # -------------------------------------------------------

        # Show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            pass

    def populate_layer_list(self, list_widget):
        """Helper to populate a QListWidget with vector layers."""
        # list_widget.clear()  # do not clear selection each time the plugin is reopened
        layers = QgsProject.instance().mapLayers().values()
        for layer in layers:
            if isinstance(layer, QgsVectorLayer):
                list_widget.addItem(layer.name())
                # Store the unique layer ID invisibly
                item = list_widget.item(list_widget.count() - 1)
                item.setData(Qt.UserRole, layer.id())

    def get_selected_layers(self, list_widget):
        """Helper to get actual layer objects from selected list items."""
        selected_layers = []
        for item in list_widget.selectedItems():
            layer_id = item.data(Qt.UserRole)
            layer = QgsProject.instance().mapLayer(layer_id)
            if layer:
                selected_layers.append(layer)
        return selected_layers

    def npw_analysis(self):
        """This function triggers when the Analysis button is clicked."""

        load_layers = self.get_selected_layers(self.dlg.listLoads)
        cable_layers = self.get_selected_layers(self.dlg.listCables)

        print("=" * 40)
        print(f"ANALYSIS TRIGGERED")
        print("=" * 40)

        print(f"\n>>> LOAD LAYERS ({len(load_layers)}) <<<")
        for layer in load_layers:
            self.print_layer_data(layer)

        print(f"\n>>> CABLE LAYERS ({len(cable_layers)}) <<<")
        for layer in cable_layers:
            self.print_layer_data(layer)

        print("\n" + "=" * 40)
        print("ANALYSIS PREVIEW FINISHED")
        print("=" * 40)

    def print_layer_data(self, layer):
        """Prints all fields and feature attributes for a given layer."""
        fields = layer.fields()
        field_names = [field.name() for field in fields]

        print(f"\nLayer Name: {layer.name()}")
        print(f"Field Names: {field_names}")
        print(f"Feature Count: {layer.featureCount()}")

        # We loop through features. Note: for very large layers,
        # this might flood the console.
        for i, feature in enumerate(layer.getFeatures()):
            # attributes() returns a list of values in order of fields
            print(f"  [Feature {i}] {feature.attributes()}")

            # Optional: stop after 20 features to prevent freezing the UI
            # if the user selects a massive dataset by accident
            if i >= 19:
                print(f"  ... (Only showing first 20 features for {layer.name()})")
                break
