# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NopywerPlugin
                                 A QGIS plugin
 power grid analysis and design tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-25
        copyright            : (C) 2026 by Victor Finel
        email                : victor.finel.pro@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NopywerPlugin class from file NopywerPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    try:
        from .setup_dependencies import setup_dependencies, get_venv_python
        from .utils import log_message
        from qgis.core import Qgis
        import os

        # Ensure dependencies are set up
        venv_path = get_venv_python()
        if not os.path.exists(os.path.dirname(venv_path)):
            # Venv doesn't exist, try to create it
            if not setup_dependencies():
                log_message(
                    "Warning: Plugin dependencies could not be installed.",
                    level=Qgis.Warning,
                )

        # load nopywer plugin class
        from .nopywer_plugin import NopywerPlugin

        return NopywerPlugin(iface)

    except Exception as e:
        # Catch any initialization errors and log them
        import traceback

        try:
            from .utils import log_message
            from qgis.core import Qgis

        except Exception as e:
            log_message(
                f"Critical error loading nopywer plugin: {str(e)}", level=Qgis.Critical
            )
            log_message(f"Traceback:\n{traceback.format_exc()}", level=Qgis.Critical)
