# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NopywerPlugin
                                 A QGIS plugin
 power grid analysis and design tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-25
        copyright            : (C) 2026 by Victor Finel
        email                : victor.finel.pro@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from .setup_dependencies import setup_dependencies
from .utils import log_message

from qgis.core import Qgis


# This runs the moment the user checks the box in the Plugin Manager
def classFactory(iface):
    try:
        # 1. Try to set up dependencies
        if not setup_dependencies(force=False, clean=False):
            # If it fails, log the error AND STOP.
            # Do not attempt to import NopywerPlugin.
            log_message(
                "CRITICAL: Dependencies failed to install. The nopywer plugin will not load.",
                level=Qgis.Critical,
            )

            # Return a dummy object so QGIS doesn't crash, but the plugin just stays hidden.
            class DummyPlugin:
                def __init__(self, iface):
                    pass

                def initGui(self):
                    pass

                def unload(self):
                    pass

            return DummyPlugin(iface)

        # 2. Only import the main plugin IF dependencies succeeded
        from .nopywer_plugin import NopywerPlugin

        return NopywerPlugin(iface)

    except Exception as e:
        import traceback

        log_message(
            f"Critical error loading nopywer plugin: {str(e)}", level=Qgis.Critical
        )
        log_message(f"Traceback:\n{traceback.format_exc()}", level=Qgis.Critical)

        class DummyPlugin:
            def __init__(self, iface):
                pass

            def initGui(self):
                pass

            def unload(self):
                pass

        return DummyPlugin(iface)
