# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NopywerPlugin
                                 A QGIS plugin
 power grid analysis and design tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-25
        copyright            : (C) 2026 by Victor Finel
        email                : victor.finel.pro@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NopywerPlugin class from file NopywerPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .setup_dependencies import setup_dependencies, get_venv_python
    from .utils import log_message
    from qgis.core import Qgis
    import os

    # Fast check: only run setup if venv is missing
    if not os.path.exists(get_venv_python()):
        if not setup_dependencies():
            log_message("Warning: Plugin dependencies could not be resolved.", level=Qgis.Critical)

    from .nopywer_plugin import NopywerPlugin

    return NopywerPlugin(iface)
