# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NopywerPlugin
                                 A QGIS plugin
 power grid analysis and design tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-04-25
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Victor Finel
        email                : victor.finel.pro@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from qgis.core import QgsProject, QgsVectorLayer, Qgis, QgsApplication, QgsMessageLog
from qgis.PyQt.QtCore import Qt

# Initialize Qt resources from file resources.py
from .resources import *

# Import the code for the dialog
from .nopywer_plugin_dialog import NopywerPluginDialog
from .exporter import NopywerExporter
from .setup_dependencies import get_venv_python, setup_dependencies
from .tasks import NopywerAnalysisTask
from qgis.core import QgsApplication
from .utils import log_message


class NopywerPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # Initialize Exporter logic
        self.exporter = NopywerExporter()

        # Keep track of running tasks to prevent garbage collection
        self.running_tasks = []

        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "NopywerPlugin_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&nopywer")

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("NopywerPlugin", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ":/plugins/nopywer_plugin/icon.png"
        self.add_action(
            icon_path,
            text=self.tr("select layers"),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr("&nopywer"), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = NopywerPluginDialog()
            # Link buttons to functions
            self.dlg.btnAnalysis.clicked.connect(self.npw_analysis_button)
            self.dlg.btnOptimize.clicked.connect(self.npw_optimize)
            self.dlg.btnExport.clicked.connect(self.npw_export)
            self.dlg.btnTest.clicked.connect(self.npw_test)
            self.dlg.btnRefresh.clicked.connect(self.npw_refresh_lib)

        # --- Populate the lists of layers ---
        self.populate_layer_list(self.dlg.listNodes)
        self.populate_layer_list(self.dlg.listCables)
        # -------------------------------------------------------

        # Show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            pass

    def populate_layer_list(self, list_widget):
        """Helper to populate a QListWidget with vector layers."""
        # list_widget.clear()  # do not clear selection each time the plugin is reopened
        layers = sorted(
            QgsProject.instance().mapLayers().values(), key=lambda layer: layer.name()
        )
        for layer in layers:
            if isinstance(layer, QgsVectorLayer):
                list_widget.addItem(layer.name())
                # Store the unique layer ID invisibly
                item = list_widget.item(list_widget.count() - 1)
                item.setData(Qt.UserRole, layer.id())

    def get_selected_layers(self, list_widget):
        """Helper to get actual layer objects from selected list items."""
        selected_layers = []
        for item in list_widget.selectedItems():
            layer_id = item.data(Qt.UserRole)
            layer = QgsProject.instance().mapLayer(layer_id)
            if layer:
                selected_layers.append(layer)
        return selected_layers

    def npw_analysis_button(self):
        """This function triggers when the Analysis button is clicked."""
        load_layers = self.get_selected_layers(self.dlg.listNodes)
        cable_layers = self.get_selected_layers(self.dlg.listCables)
        log_message(f"Selected load layers: {[l.name() for l in load_layers]}")
        log_message(f"Selected cable layers: {[l.name() for l in cable_layers]}")
        self.npw_analysis(load_layers, cable_layers)

    def npw_analysis(self, load_layers, cable_layers):
        log_message(f"npw_analysis triggered with {len(load_layers)} loads and {len(cable_layers)} cables")

        # 0. Get power unit multiplier
        unit = self.dlg.cmbPowerUnits.currentText()
        scale = 1000.0  # Default kW
        if unit == "W":
            scale = 1.0
        elif unit == "MW":
            scale = 1000000.0
        log_message(f"Using power scale factor: {scale} (selected unit: {unit})")

        # 1. Preview and Export to GeoJSON
        paths = self.exporter.run_preview(
            load_layers, cable_layers, power_units_scale=scale
        )

        if not paths:
            log_message("Export failed, no GeoJSON path returned.", Qgis.Warning)
            self.iface.messageBar().pushMessage(
                "Nopywer", "No valid layers selected for export.", Qgis.Warning
            )
            return

        geojson_in, geojson_out = paths

        # 2. Setup Task
        python_exe = get_venv_python()
        task = NopywerAnalysisTask(
            "Nopywer Grid Analysis", python_exe, geojson_in, geojson_out
        )

        # 3. Start Task
        # Hold reference to prevent garbage collection
        self.running_tasks.append(task)
        # Optional: Clean up list when task is done
        task.taskCompleted.connect(
            lambda: self.running_tasks.remove(task)
            if task in self.running_tasks
            else None
        )

        QgsApplication.taskManager().addTask(task)

        self.iface.messageBar().pushMessage(
            "Nopywer", "Analysis started in background...", Qgis.Info
        )

    def npw_optimize(self):
        log_message("Optimization is not implemented yet", Qgis.Warning)

    def npw_export(self):
        log_message("Export button has no effect yet", Qgis.Warning)

    def npw_test(self):
        log_message("Running test procedure...")
        layer_names_load = ["test_nodes"]
        layer_names_cable = [
            "test_1phase",
            "test_3phases_32a",
            "test_3phases_63a",
        ]

        # Get actual layer objects from project by name
        all_layers = QgsProject.instance().mapLayers().values()
        load_layers = [
            layer for layer in all_layers if layer.name() in layer_names_load
        ]
        cable_layers = [
            layer for layer in all_layers if layer.name() in layer_names_cable
        ]

        self.npw_analysis(load_layers, cable_layers)

    def npw_refresh_lib(self):
        """Force re-install of nopywer library."""
        log_message("Refreshing nopywer library...", Qgis.Info)
        self.iface.messageBar().pushMessage(
            "Nopywer", "Refreshing nopywer library...", Qgis.Info
        )

        # This will block the UI briefly while uv does its magic
        # We pass force=True to trigger the update logic
        success = setup_dependencies(force=True)

        if success:
            log_message("nopywer successfully refreshed!", Qgis.Success)
            self.iface.messageBar().pushMessage(
                "Nopywer", "nopywer successfully refreshed!", Qgis.Success
            )
        else:
            error_msg = "Failed to refresh nopywer. Check console/log for details."
            log_message(error_msg, Qgis.Critical)
            self.iface.messageBar().pushMessage(
                "Nopywer",
                error_msg,
                Qgis.Critical,
            )
